PT-850: Pending in Plugins for SW6
mondu-ai/bnpl-checkout-shopware6 pull request #58
Opened 2024-01-15 13:43 UTC by ivan-pugach-mondu

## Description

This PR aims to improve the order process and assign the proper status on the Shopware side when the payment goes through the pending flow

Fixes # (issue)
https://mondu.atlassian.net/browse/PT-850

- [X] New feature (non-breaking change which adds functionality)
- [X] This change requires a documentation update

## Checklist:
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have checked my code and corrected any misspellings

2024-01-15 14:13 UTC, Yaroslavzev submitted a review, later dismissed
utACK 👍 

**suggestion(non-blocking)**: from my prospective it would be nice to have place with conditions and it will help to maintain codebase in the future. This place can be hash, service object which contain mapping between transaction and responce statuses or humane readable method. 
For example this two lines
```
                $confirmResponseState != 'confirmed' &&
                $confirmResponseState != 'pending'
```
can be moved to method with name `orderConfirmed?`
Please note that I am fine to leave as it's now.

2024-01-15 16:23 UTC, arthurmmoreira approved these changes
utACK

2024-01-15 16:23 UTC, arthurmmoreira commented on src/Components/Webhooks/Controller/WebhooksController.php
> -        case 'order/canceled':
Nice 👍

2024-01-15 16:43 UTC, ume3119 commented
@ivan-pugach-mondu @tikohov20  can it be deployed on our stage for testing?

2024-01-16 10:00 UTC, tikohov20 commented
> @ivan-pugach-mondu @tikohov20 can it be deployed on our stage for testing?

I'll deploy it to stage.

2024-01-16 13:24 UTC, tikohov20 requested changes

2024-01-16 13:24 UTC, tikohov20 commented on src/Components/PaymentMethod/PaymentHandler/MonduHandler.php
> +        return $confirmResponseState != self::RESPONSE_STATE_CONFIRMED && $confirmResponseState != self::RESPONSE_STATE_PENDING;
is this part correct?

for example lets assume $confirmResponseState is confirmed

in this case $confirmResponseState != confirmed so this function will return false.

I think we should change this to 

`
return in_array($confirmResponseState, [self::RESPONSE_STATE_CONFIRMED, self::RESPONSE_STATE_PENDING]);
`

2024-01-16 13:29 UTC, tikohov20 commented
Lets update the composer.json file and update the version there in this pr.

2024-01-16 16:34 UTC, ivan-pugach-mondu commented on src/Components/PaymentMethod/PaymentHandler/MonduHandler.php
> +        return $confirmResponseState != self::RESPONSE_STATE_CONFIRMED && $confirmResponseState != self::RESPONSE_STATE_PENDING;
Thank you @tikohov20, good catch. I did the update, please review once again

2024-01-17 08:53 UTC, tikohov20 submitted a review, later dismissed

2024-01-24 08:06 UTC, tikohov20 approved these changes

2024-01-24 08:07 UTC, merged